apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volume.name }}
spec:
  capacity:
    storage: {{ .Values.volume.capacity }}
  volumeMode: {{ .Values.volume.mode }}
  accessModes:
    - {{ .Values.volume.persistentvolumeclaim.accessmodes }}
  persistentVolumeReclaimPolicy: {{ .Values.volume.persistentvolumereclaimpolicy }}
  storageClassName: {{ .Values.storageclass.name }}
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}
    readOnly: {{ .Values.nfs.readonly }}