- name: Update kube-proxy configmap
  ansible.builtin.shell:
    cmd: |
      kubectl get configmap kube-proxy -n kube-system -o yaml | sed -e "s/strictARP: false/strictARP: true/" | kubectl apply -f - -n kube-system
    executable: /bin/bash

- name: install metallb manifest
  shell: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.3/config/manifests/metallb-native.yaml