volume:
  name: nfs-pv
  capacity: 1Gi
  mode: Filesystem
  persistentvolumereclaimpolicy: Retain
  volumemount:
    name: nfs-persistent-storage
  persistentvolumeclaim:
    name: nfs-pvc
    accessmodes: ReadWriteOnce

storageclass:
  name: nfs-storage

nfs:
  server: 192.168.100.112
  path: "/srv/nfs/kubedata" 
  readonly: false