- hosts: all
  become: yes
  gather_facts: no
  roles:
    - name_resolution

- hosts: all
  roles:
    - ipv4_bridge
    - kube_dependencies

- hosts: masters
  roles:
    - master_init
    - master_token_create

- hosts: workers
  roles:
    - workers_join

- hosts: masters
  roles:
    - metallb
    - ingress

- hosts: masters
  roles: 
    - add_kubectl_to_host

- hosts: masters
  roles:
    - get_ingress_controler_ip

- hosts: all
  become: yes
  roles:
    - add_ingress_controler_to_hosts_command
    - allow_insecure_registries