- name: Ensure Docker directory exists
  file:
    path: /etc/docker
    state: directory

- name: Create Docker daemon.json if it doesn't exist
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "insecure-registries" : ["registry.nginx-app.info"]
      }
  when: not ansible_check_mode

- name: Update containerd config.toml
  blockinfile:
    path: /etc/containerd/config.toml
    block: |
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry.nginx-app.info"]
        endpoint = ["https://registry.nginx-app.info"]
      [plugins."io.containerd.grpc.v1.cri".registry.configs."registry.nginx-app.info".tls]
        insecure_skip_verify = true
      [plugins."io.containerd.grpc.v1.cri".registry.configs."registry.nginx-app.info".auth]
        password = "Harbor12345"
        username = "admin"

- name: Restart containerd service
  systemd:
    name: containerd
    state: restarted

- name: Restart Docker service
  systemd:
    name: docker
    state: restarted